spring:
  #配置Druid数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://119.23.63.134:3306/mooc?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: Mooc123456
      platform: mysql

mybatis:
  mapper-locations: classpath:mapper/*.xml   #配置Mapper.xml文件所在路径
  type-aliases-package: com.nebula.mooc.core.entity   #配置pojo位置
