spring:
  profiles:
    active: core
  # 配置邮件
  mail:
    host: smtp.163.com
    username: nebulamooc@163.com
    password: mooc123456
    default-encoding: UTF-8
    port: 465 # 一般服务器的25端口会被禁用导致无法连接邮件服务器
    properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  redis:
    database: 1  # 使用索引为1的数据库作为缓存

port:
  http: 80
  https: 443

server:
  #ssl的端口
  port: ${port.https}
  ssl:
    #证书的路径
    key-store: classpath:nebulamooc.pfx
    #证书密码
    key-store-password: 4qDeSwsh
    #秘钥库类型
    key-store-type: PKCS12

# FastDFS配置
fdfs:
  connectTimeout: 10
  networkTimeout: 60
  charset: UTF-8
  # 可填写多个，以逗号分隔
  trackerServerAddress: ${fastdfs_ip}:22122
