spring:
  profiles:
    active: core
  # 配置邮件
  mail:
    host: smtp.163.com
    username: nebulamooc@163.com
    password: mooc123456
    default-encoding: UTF-8

port:
  http: 80
  https: 443

server:
  #ssl的端口
  port: ${port.https}
  ssl:
    #证书的路径
    key-store: classpath:nebulamooc.top.pfx
    #证书密码
    key-store-password: 4qDeSwsh
    #秘钥库类型
    key-store-type: PKCS12
