spring:
  profiles:
    active: core

websocket:
  port: 9080
  path: /websocket

tcp:
  backlog: 1024
  keepalive: true
  noDelay: true

ssl:
  certpath: nebulamooc.top.pem
  keypath: nebulamooc.top.key
  password: 4qDeSwsh
