spring:
  profiles:
    active: core

redis:
  # scheme://[user:password@]domain:port
  addresses: redis://root:Mooc123456@${server_ip}:6379
  expireMinutes: 120
  maxTotal: 16
  maxIdle: 8
  minIdle: 2
  maxWaitMillis: 10000  # 获取连接时的最大等待毫秒数(如果设置为阻塞时BlockWhenExhausted),如果超时就抛异常, 小于零:阻塞不确定的时间, 默认-1
  timeBetweenEvictionRunsMillis: 30000  # 表示idle object evitor两次扫描之间要sleep的毫秒数
  numTestsPerEvictionRun: 8 # 表示idle object evitor每次扫描的最多的对象数
  minEvictableIdleTimeMillis: 30000 # 表示一个对象至少停留在idle状态的最短时间，然后才能被idle object evitor扫描并驱逐；这一项只有在timeBetweenEvictionRunsMillis大于0时才有意义
