# 导入yml配置文件
spring:
  profiles:
    include: core

server:
  port: 8080

redis:
  # scheme://[user:password@]domain:port/path?query_string#fragment_id
  address: redis://root:Mooc123456@119.23.63.134:6379
  expire-minute: 120
